### ISSUE TITLE
Add button to remove bill from recent

### ISSUE THREAD

**Issue by Balastrong** [DevLeonardoCommunity/billsplit#10]
I think about a red X button next to each recent to remove it from localStorage

![image](https://github.com/DevLeonardoCommunity/billsplit/assets/7253929/c182d2da-80af-4524-b61c-74f6e80c94e8)

**Comment by K1ethoang** [comment]
Can i try to do it?

**Comment by Balastrong** [comment]
Sure! Go head :)

**Comment by K1ethoang** [comment]
Hey @Balastrong , can you check my PR #22 ?

**Comment by K1ethoang** [comment]
We have done, you can close this issue
