### ISSUE TITLE
Can not set up to run on local to dev

### ISSUE THREAD

**Issue by K1ethoang** [DevLeonardoCommunity/billsplit#18]
### Describe your issue

Error message: 

![image](https://github.com/DevLeonardoCommunity/billsplit/assets/88199151/28502ef4-aaa1-4199-b897-50e6aac1c85d)

### Steps to reproduce

...

### Would you like to work on this issue?

None

**Comment by K1ethoang** [comment]
@Balastrong Help me

**Comment by Balastrong** [comment]
I'm also having issues now on setting up locally, let's see if we can get some help from other community members :)

**Comment by Balastrong** [comment]
Hey @K1ethoang, thanks for your patience!

I added rollup in #19 and seems like it's working on linux, could you please sync your fork and try again?

**Comment by K1ethoang** [comment]
> Hey @K1ethoang, thanks for your patience!
> 
> 
> 
> I added rollup in #19 and seems like it's working on linux, could you please sync your fork and try again?

Ok, I will sync my fork and try again

**Comment by K1ethoang** [comment]
hey @Balastrong, I use command `npm install --include=optional sharp` and after install, I `npm run dev`, result: 

I think use should add `"sharp": "^0.33.2"` in dependencies below `"@supabase/supabase-js"`

![image](https://github.com/DevLeonardoCommunity/billsplit/assets/88199151/153f71f0-01f3-4891-810d-9b420381aa20)

**Comment by Balastrong** [comment]
Do you want to open a PR with the updated package.json?

**Comment by K1ethoang** [comment]
> Do you want to open a PR with the updated package.json?

Yes, I will do it

**Comment by K1ethoang** [comment]
@Balastrong, I have opened PR, can u check it?
