### ISSUE TITLE
supabaseUrl is required

### ISSUE THREAD

**Issue by K1ethoang** [DevLeonardoCommunity/billsplit#20]
### Describe your issue

![image](https://github.com/DevLeonardoCommunity/billsplit/assets/88199151/e8024aea-6269-41ea-a7d2-bbb38a873351)

### Steps to reproduce

...

### Would you like to work on this issue?

None

**Comment by Balastrong** [comment]
As we're in really early stages there's no local db but we can point to the same hosted, instructions are here: https://github.com/DevLeonardoCommunity/billsplit/blob/main/CONTRIBUTING.md#environment-variables

With #13 we'll have a local db for testing.

Let me know if setting the env fixes the issue, also thanks a lot for testing the project setup!!

**Comment by K1ethoang** [comment]
> As we're in really early stages there's no local db but we can point to the same hosted, instructions are here: https://github.com/DevLeonardoCommunity/billsplit/blob/main/CONTRIBUTING.md#environment-variables
> 
> 
> 
> With #13 we'll have a local db for testing.
> 
> 
> 
> Let me know if setting the env fixes the issue, also thanks a lot for testing the project setup!!

Sorry about that ^^, I remember reading that file :)
