### ISSUE TITLE
Show the time in the recent bills history

### ISSUE THREAD

**Issue by Balastrong** [DevLeonardoCommunity/billsplit#9]
In the homepage we only display the date. The time might help (hour and minute should be enough)

![image](https://github.com/DevLeonardoCommunity/billsplit/assets/7253929/08e1dae0-e2aa-4221-966a-f6b80a87b3ce)

**Comment by K1ethoang** [comment]
I can do it

**Comment by Balastrong** [comment]
Ok, go for it! :D
